alter table YESS_INCIDENT add constraint FK_YESS_INCIDENT_INCIDENT_REGION_ID foreign key (INCIDENT_REGION_ID) references YESS_REGION(ID);
create index IDX_YESS_INCIDENT_INCIDENT_REGION on YESS_INCIDENT (INCIDENT_REGION_ID);
