alter table YESS_FAMILY add constraint FK_YESS_FAMILY_DEATH_IN_INCIDENT_ID foreign key (DEATH_IN_INCIDENT_ID) references YESS_INCIDENT(ID);
create index IDX_YESS_FAMILY_DEATH_IN_INCIDENT on YESS_FAMILY (DEATH_IN_INCIDENT_ID);
