-- begin YESS_REGION
create unique index IDX_YESS_REGION_UNIQ_REGION_NAME on YESS_REGION (REGION_NAME) ^
-- end YESS_REGION
-- begin YESS_CITY
alter table YESS_CITY add constraint FK_YESS_CITY_REGION_ID foreign key (REGION_ID) references YESS_REGION(ID)^
create index IDX_YESS_CITY_REGION on YESS_CITY (REGION_ID)^
-- end YESS_CITY
-- begin YESS_INCIDENT
alter table YESS_INCIDENT add constraint FK_YESS_INCIDENT_INCIDENT_REGION_ID foreign key (INCIDENT_REGION_ID) references YESS_REGION(ID)^
alter table YESS_INCIDENT add constraint FK_YESS_INCIDENT_INCIDENT_CITY_ID foreign key (INCIDENT_CITY_ID) references YESS_CITY(ID)^
create index IDX_YESS_INCIDENT_INCIDENT_CITY on YESS_INCIDENT (INCIDENT_CITY_ID)^
create index IDX_YESS_INCIDENT_INCIDENT_REGION on YESS_INCIDENT (INCIDENT_REGION_ID)^
-- end YESS_INCIDENT
-- begin YESS_FAMILY
alter table YESS_FAMILY add constraint FK_YESS_FAMILY_CITY_ID foreign key (CITY_ID) references YESS_CITY(ID)^
alter table YESS_FAMILY add constraint FK_YESS_FAMILY_DEATH_IN_INCIDENT_ID foreign key (DEATH_IN_INCIDENT_ID) references YESS_INCIDENT(ID)^
create index IDX_YESS_FAMILY_DEATH_IN_INCIDENT on YESS_FAMILY (DEATH_IN_INCIDENT_ID)^
create index IDX_YESS_FAMILY_CITY on YESS_FAMILY (CITY_ID)^
-- end YESS_FAMILY
-- begin YESS_SPONSORED
alter table YESS_SPONSORED add constraint FK_YESS_SPONSORED_CITY_ID foreign key (CITY_ID) references YESS_CITY(ID)^
alter table YESS_SPONSORED add constraint FK_YESS_SPONSORED_FAMILY_ID foreign key (FAMILY_ID) references YESS_FAMILY(ID)^
create index IDX_YESS_SPONSORED_CITY on YESS_SPONSORED (CITY_ID)^
create index IDX_YESS_SPONSORED_FAMILY on YESS_SPONSORED (FAMILY_ID)^
-- end YESS_SPONSORED
-- begin YESS_SPONSORSHIP_REQUEST
alter table YESS_SPONSORSHIP_REQUEST add constraint FK_YESS_SPONSORSHIP_REQUEST_APPLICANT_ID foreign key (APPLICANT_ID) references YESS_SPONSORED(ID)^
create index IDX_YESS_SPONSORSHIP_REQUEST_APPLICANT on YESS_SPONSORSHIP_REQUEST (APPLICANT_ID)^
-- end YESS_SPONSORSHIP_REQUEST
-- begin YESS_PROVIDER
alter table YESS_PROVIDER add constraint FK_YESS_PROVIDER_CITY_ID foreign key (CITY_ID) references YESS_CITY(ID)^
create index IDX_YESS_PROVIDER_CITY on YESS_PROVIDER (CITY_ID)^
-- end YESS_PROVIDER
